def get_preguntas(tema, i):
    return preguntas_dict[tema][i]

def get_respuestas(tema,i):
    return respuestas_dict[tema][i]

preguntas_dict = {
    "Animales":     [ "Cuál es el animal más grande del mundo?", 
                     "Qué animal vuela y hace miel?",
                     "Cuál es el animal más rápido del mundo?",
                     "Qué animal tiene una joroba en la espalda?",
                     "Qué animal es conocido por su trompa larga?",
                     "Qué animal tiene una melena y ruge?",
                     "Cuál es el animal que puede nadar y volar?",
                     "Qué animal tiene rayas negras y blancas?",
                     "Qué animal tiene manchas negras y blancas?",
                     "Cuál es el animal que hiberna durante el invierno?"],
    "Paises":       ["Cuál es el país más poblado del mundo?", 
                     "En qué país se encuentra la Torre Eiffel?", 
                     "Cuál es el país más grande de América Latina?",
                     "En qué país se encuentra la Gran Muralla China?",
                     "Cuál es el país más pequeño del mundo?",
                     "En qué país se encuentra la ciudad de Roma?",
                     "Cuál es el país más grande de África?",
                     "En qué país se encuentra el Taj Mahal?",
                     "Cuál es el país más grande de Europa?",
                     "En qué país se encuentra la ciudad de Atenas?"],
    "Profesiones":  ["Cuál es la profesión que se encarga de cuidar los dientes?", 
                     "Qué profesión se dedica a construir edificios? ",
                     "Qué profesión se ocupa de defender a las personas acusadas?",
                     "Qué profesión se dedica a cuidar y tratar a los animales enfermos?",
                     "Cuál es la profesión que se encarga de apagar incendios?",
                     "Qué profesión se dedica a enseñar en las escuelas?",
                     "Cuál es la profesión que se ocupa de pilotar aviones?",
                     "Qué profesión se dedica a diseñar puentes y carreteras?",
                     "Cuál es la profesión que se encarga de la salud de las personas?",
                     "Qué profesión se dedica a escribir noticias?"],
    "Deportes":     ["En qué deporte se utiliza una raqueta para golpear una pelota?",
                     "Cuál es el deporte más popular en Estados Unidos?",
                     "En qué deporte se lanza un disco hacia una diana?",
                     "Cuál es el deporte que se juega en una pista y se corre en círculos?",
                     "En qué deporte se utiliza un palo para golpear una bola en un hoyo?",
                     "Cuál es el deporte en el que se lucha cuerpo a cuerpo en un tatami?",
                     "En qué deporte se utiliza una tabla para deslizarse sobre las olas?",
                     "Cuál es el deporte que se juega sobre hielo y con un disco?",
                     "En qué deporte se corre, se salta y se lanza una jabalina?",
                     "Cuál es el deporte en el que dos equipos compiten por marcar goles?"],
    "Instrumentos": ["Cuál es el instrumento de cuerda que se toca con un arco?",
                     "Qué instrumento de percusión se toca con las manos?",
                     "Instrumento de viento que se toca soplando y tiene llaves?",
                     "Qué instrumento de teclado tiene 88 teclas?",
                     "Instrumento de viento que se toca soplando y tiene tres válvulas?",
                     "Qué instrumento de percusión se toca con baquetas y tiene platillos?",
                     "Instrumento de cuerda que se toca con los dedos y tiene trastes?",
                     "Instrumento que se toca soplando con una boquilla y tiene teclas?",
                     "Cuál es el instrumento de cuerda que es más grande que el violín?",
                     "Instrumento que se toca con las manos y tiene forma de media luna?"],
    "Cuerpo":       ["Cuál es el órgano que bombea la sangre?",
                     "Qué parte del cuerpo contiene los dientes?",
                     "Cuál es el hueso largo de la parte superior del brazo?",
                     "Qué parte del cuerpo se utiliza para oler?",
                     "Cuál es el órgano principal del sistema nervioso?",
                     "Qué parte del cuerpo contiene los pulmones?",
                     "Cuál es el hueso más largo del cuerpo?",
                     "Qué parte del cuerpo contiene el estómago?",
                     "Cuál es el músculo principal en la parte posterior de la pierna?",
                     "Qué parte del cuerpo se utiliza para ver?"],
    "Transporte":   ["Qué medio de transporte se utiliza para volar en el aire?",
                     "Medio de transporte que se utiliza para navegar en el agua?",
                     "Qué medio de transporte se utiliza para viajar sobre rieles?",
                     "Medio de transporte que se utiliza en ciudad y tiene dos ruedas?",
                     "Medio de transporte personal que tiene cuatro ruedas?",
                     "Medio de transporte que tiene dos ruedas y un motor?",
                     "Medio de transporte para navegar en el agua y más pequeño que un barco?",
                     "Medio de transporte que es tirado por caballos?",
                     "Medio de transporte recreativo marítimo?",
                     "Medio de transporte con tres ruedas para niños?"],
    "Rios":         ["Cuál es el río más largo de España?",
                     "Cuál es el río que atraviesa Madrid?",
                     "Cuál es el río que separa España de Portugal?",
                     "Cuál es el río que pasa por Sevilla?",
                     "Río que nace en los Picos de Europa y desemboca en el Cantábrico?",
                     "Cuál es el río que pasa por Barcelona?",
                     "Río que forma la frontera natural entre España y Francia?",
                     "Cuál es el río que atraviesa Zaragoza?",
                     "Cuál es el río que atraviesa Valencia?",
                     "Río que nace en Cazorla y desemboca en el Mar Mediterráneo?"]                                    
}

respuestas_dict = {
    "Animales": ["Cebra","Ballena","Abeja","Guepardo","Camello","Elefante","León","Pato","Tigre","Oso"],
    "Países": ["China","Francia","Brasil","China","Vaticano","Italia","Argelia","India","Rusia","Grecia"],
    "Profesiones": ["Dentista","Constructor","Abogado","Veterinario","Bombero","Maestro","Piloto","Ingeniero","Médico","Periodista"],
    "Colores": ["Morado","Rojo","Verde","Amarillo","Naranja","Blanco","Verde","Azul","Rosa","Azul"],
    "Deportes": ["Tenis","Beisbol","Frisbee","Atletismo","Golf","Judo","Surf","Hockey","Atletismo","Fútbol"],
    "Instrumentos": ["Violín","Timba","Clarinete","Piano","Trompeta","Batería","Guitarra","Saxofón","Violonchelo","Cajón"],
    "Cuerpo": ["Corazón","Boca","Húmero","Nariz","Cerebro","Pecho","Fémur","Abdomen","Gemelos","Ojos"],
    "Transporte": ["Avión","Barco","Tren","Bicicleta","Coche","Motocicleta","Bote","Carroza","Yate","Triciclo"],
    "Ríos": ["Ebro","Manzanares","Miño","Guadalquivir","Sella","Llobregat","Bidasoa","Ebro","Turia","Guadalquivir"]
}